In [109]:
import pandas as pd
df1= pd.read_excel(io= "/Users/hp/Downloads/Bank_Transactions_Feb2025_Jan2026.xlsx",sheet_name="Sheet1")

In [114]:
df1.drop(0,axis=0,inplace=True)

In [118]:
df1.columns = final.columns

In [120]:
df1.shape

(452, 6)

In [107]:
df1.drop(0,inplace=True)

In [63]:
df1.columns =df1.iloc[0,:]

In [54]:
df1.drop(["Column3","Column5","Column9"],axis=1,inplace=True)

In [26]:
d = df1.dropna(subset="Date",)

In [8]:
df_1 = df1.dropna().reset_index(drop=True)

In [75]:
d = df1.drop("Transaction Type",axis=1)

In [77]:
final.drop("Unnamed: 6",axis=1,inplace=True)

In [96]:
d.columns = final.columns

In [95]:
final.columns

Index(['Date', 'Particulars', 'Chq No/ReF No', 'Withdrawal', 'Deposit',
       'Balance'],
      dtype='object')

In [121]:
final = pd.concat([final,df1])

In [122]:
final.shape

(1119, 6)

In [92]:
final.drop(["Date(Value Date)","Ref No.\n/Cheque No","Debit(Rs)","Credit(Rs)","Balance(Rs)"],axis=1,inplace=True)

In [100]:
final

,Date,Particulars,Chq No/ReF No,Withdrawal,Deposit,Balance
0,26 Jan 2026,UPI/602641260853/DR/Go,S23333308,300.9,0.0,0.3
1,25 Jan 2026,UPI/602512447086/DR/Pol,S19468207,2201.0,0.0,301.2
2,25 Jan 2026,UPI/639190202642/CR/SA,S19408960,0.0,1600.0,2502.2
3,25 Jan 2026,UPI/602535643841/DR/SU,S17890671,20.0,0.0,902.2
4,25 Jan 2026,UPI/639128987799/DR/Ind,S9835450,215.0,0.0,922.2
...,...,...,...,...,...,...
116,12-Nov-25 (12-Nov-25),UPI/531620277109/DR/mr yadav velum\n/YES/UPI,S73555077,50,-,420.65
117,11-Nov-25 (11-Nov-25),UPI/531524570486/DR/PRADHAN MANTRI/YES/UPI,S67910845,180,-,470.65
118,11-Nov-25 (11-Nov-25),UPI/531549327455/DR/PRADEEP KUMAR /UBI/UPI,S56491791,25,-,650.65
119,11-Nov-25 (11-Nov-25),APY-SI/MNTLY/QTRLY/HLFRLY\n/YRLY,S50359573,248,-,675.65
120,11-Nov-25 (11-Nov-25),Int.Pd:01-08-2025 to 31-10-2025:\n129501000015436,S50019235,-,86,923.65

In [124]:
final.to_excel("iob_and_indusind_and_Kotak.xlsx")

In [ ]:
impo

In [137]:
final.loc[:,"Withdrawal"].replace("-",0,inplace=True)

/var/folders/tn/6j9xy4y51cnbfstw_b9jl9mr0000gn/T/ipykernel_9635/2086570236.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final.loc[:,"Withdrawal"].replace("-",0,inplace=True)

In [139]:
final["Withdrawal"] = final["Withdrawal"].astype(float)

In [144]:
final.sort_values(by="Withdrawal",ascending=False)

,Date,Particulars,Chq No/ReF No,Withdrawal,Deposit,Balance
2,22-Jan-26 (22-Jan-26),UPI/602290649727/DR/sangeetaprajap\n/IOB/UPI,S29484787,37000.0,-,184.65
14,25-Dec-25 (25-Dec-25),UPI/535905504922/DR/ KALURAM/YES\n/Verified,S94155372,25000.0,-,50.02
310,26 May 2025,UPI/HIRA OMKAR GENE/551209013060/UPI,UPI-514632119455,20000.0,NaN,626.29
479,24 Feb 2025,ATM CASH TXN/INDUSIND BANK LIMITED MUMBAI M H,S50777184,20000.0,0.0,20544.99
384,17 Jun 2025,UPI/HIRA OMKAR GENE/516811421395/UPI,UPI-516804940838,19700.0,NaN,218.29
...,...,...,...,...,...,...
438,15 Jan 2026,UPI/MR RUSHABH VIJA/601564142059/Payment from sl,UPI-601564348998,NaN,350.0,350.1
443,28 Jan 2026,UPI/HITESH KUKARAM /602870337205/UPI,UPI-602833663560,NaN,120.0,146.1
445,30 Jan 2026,Recd:IMPS/603031559568/GOOGLEINDI/KKBK /X2063/...,IMPS-603012153086,NaN,5000.0,5126.1
447,30 Jan 2026,UPI/JYOTI ARUN KUMA/603079413289/UPI,UPI-603091834106,NaN,2000.0,2126.1
448,30 Jan 2026,UPI/JYOTI ARUN KUMA/603043018147/UPI,UPI-603091859087,NaN,8000.0,10126.1