# Pandas

In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-2.2.0-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy<2,>=1.26.0 (from pandas)
  Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 61.0/61.0 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2023.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.0-cp312-cp312-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/11.5 MB 5.9 MB/s eta 0:00:02
   -- ------------------------------------- 0.6/11.5 MB 6.8 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/11.5 MB 6.3 MB/s eta 0:00:02
   ---- ----------------------------------- 1.4/11.5 MB 6.4 MB/s eta 0:00:02
   ------ --------------------------------- 1.9/11.5 MB 6.6 MB/s eta 0:00:02
   -------- ------------------------------- 2.3/11.5 MB 6.5 MB/s eta 0:00:02
   --------- ------------------------------ 2.8/11.5 MB 6.6 MB/s eta 0:00:02
   ----------- ---------------------------- 3.3/11.5 MB 6.6 MB/s eta 0:00:02
   ------------ --------------------------- 3.6/11.5 MB 6.3 MB/s eta 0:00:02
   ------------ --------------------------- 3.7/11.5 MB 5.9 MB/s eta 0:00:02
   ------------- -------------------------- 3.9/11.5 MB 5.5 MB/s eta 0:00:02
   -------------- ------------------------- 4.1/11.5 MB 5.3 MB/s eta 0:00:02
   -------------- ------------------------- 4.3/11.5 MB 5.1 MB/s eta 0:00:02
   --------------- ------------------------ 4.5/11.5 MB 5.0 MB/s eta 0:00:02
   ---------------- ----------------------- 4.6/11.5 MB 4.8 MB/s eta 0:00:02
   ---------------- ----------------------- 4.8/11.5 MB 4.7 MB/s eta 0:00:02
   ----------------- ---------------------- 5.0/11.5 MB 4.6 MB/s eta 0:00:02
   ------------------ --------------------- 5.3/11.5 MB 4.6 MB/s eta 0:00:02
   ------------------ --------------------- 5.3/11.5 MB 4.5 MB/s eta 0:00:02
   ------------------- -------------------- 5.5/11.5 MB 4.3 MB/s eta 0:00:02
   --------------------- ------------------ 6.1/11.5 MB 4.5 MB/s eta 0:00:02
   ---------------------- ----------------- 6.5/11.5 MB 4.5 MB/s eta 0:00:02
   ------------------------ --------------- 7.0/11.5 MB 4.7 MB/s eta 0:00:01
   -------------------------- ------------- 7.5/11.5 MB 4.8 MB/s eta 0:00:01
   --------------------------- ------------ 8.0/11.5 MB 4.9 MB/s eta 0:00:01
   ----------------------------- ---------- 8.4/11.5 MB 5.0 MB/s eta 0:00:01
   ------------------------------- -------- 9.0/11.5 MB 5.1 MB/s eta 0:00:01
   -------------------------------- ------- 9.3/11.5 MB 5.1 MB/s eta 0:00:01
   ---------------------------------- ----- 9.8/11.5 MB 5.2 MB/s eta 0:00:01
   ------------------------------------ --- 10.4/11.5 MB 5.3 MB/s eta 0:00:01
   ------------------------------------- -- 10.9/11.5 MB 5.4 MB/s eta 0:00:01
   -------------------------------------- - 11.1/11.5 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  11.4/11.5 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.5 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.5 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 4.9 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
    --------------------------------------- 0.3/15.5 MB 8.9 MB/s eta 0:00:02
   -- ------------------------------------- 0.9/15.5 MB 7.8 MB/s eta 0:00:02
   --- ------------------------------------ 1.4/15.5 MB 8.1 MB/s eta 0:00:02
   ---- ----------------------------------- 1.9/15.5 MB 8.2 MB/s eta 0:00:02
   ----- ---------------------------------- 2.1/15.5 MB 7.0 MB/s eta 0:00:02
   ----- ---------------------------------- 2.2/15.5 MB 6.5 MB/s eta 0:00:03
   ------ --------------------------------- 2.7/15.5 MB 6.3 MB/s eta 0:00:03
   ------- -------------------------------- 2.9/15.5 MB 6.5 MB/s eta 0:00:02
   ------- -------------------------------- 3.1/15.5 MB 5.8 MB/s eta 0:00:03
   -------- ------------------------------- 3.4/15.5 MB 5.7 MB/s eta 0:00:03
   --------- ------------------------------ 3.6/15.5 MB 5.5 MB/s eta 0:00:03
   --------- ------------------------------ 3.8/15.5 MB 5.4 MB/s eta 0:00:03
   ---------- ----------------------------- 4.3/15.5 MB 5.6 MB/s eta 0:00:03
   ----------- ---------------------------- 4.5/15.5 MB 5.5 MB/s eta 0:00:02
   ------------ --------------------------- 4.7/15.5 MB 5.4 MB/s eta 0:00:03
   ------------ --------------------------- 5.0/15.5 MB 5.4 MB/s eta 0:00:02
   ------------- -------------------------- 5.3/15.5 MB 5.3 MB/s eta 0:00:02
   -------------- ------------------------- 5.5/15.5 MB 5.1 MB/s eta 0:00:02
   --------------- ------------------------ 5.9/15.5 MB 5.4 MB/s eta 0:00:02
   --------------- ------------------------ 6.2/15.5 MB 5.2 MB/s eta 0:00:02
   ---------------- ----------------------- 6.4/15.5 MB 5.2 MB/s eta 0:00:02
   ---------------- ----------------------- 6.5/15.5 MB 5.1 MB/s eta 0:00:02
   ---------------- ----------------------- 6.5/15.5 MB 4.9 MB/s eta 0:00:02
   ---------------- ----------------------- 6.6/15.5 MB 4.8 MB/s eta 0:00:02
   ---------------- ----------------------- 6.6/15.5 MB 4.8 MB/s eta 0:00:02
   ----------------- ---------------------- 6.8/15.5 MB 4.5 MB/s eta 0:00:02
   ------------------ --------------------- 7.3/15.5 MB 4.6 MB/s eta 0:00:02
   ------------------- -------------------- 7.7/15.5 MB 4.7 MB/s eta 0:00:02
   ------------------- -------------------- 7.7/15.5 MB 4.7 MB/s eta 0:00:02
   ------------------- -------------------- 7.7/15.5 MB 4.5 MB/s eta 0:00:02
   -------------------- ------------------- 7.8/15.5 MB 4.3 MB/s eta 0:00:02
   -------------------- ------------------- 7.9/15.5 MB 4.3 MB/s eta 0:00:02
   -------------------- ------------------- 7.9/15.5 MB 4.3 MB/s eta 0:00:02
   -------------------- ------------------- 7.9/15.5 MB 4.3 MB/s eta 0:00:02
   -------------------- ------------------- 7.9/15.5 MB 4.3 MB/s eta 0:00:02
   -------------------- ------------------- 7.9/15.5 MB 4.3 MB/s eta 0:00:02
   -------------------- ------------------- 8.0/15.5 MB 3.7 MB/s eta 0:00:03
   -------------------- ------------------- 8.1/15.5 MB 3.6 MB/s eta 0:00:03
   -------------------- ------------------- 8.1/15.5 MB 3.6 MB/s eta 0:00:03
   -------------------- ------------------- 8.1/15.5 MB 3.5 MB/s eta 0:00:03
   --------------------- ------------------ 8.2/15.5 MB 3.5 MB/s eta 0:00:03
   --------------------- ------------------ 8.3/15.5 MB 3.4 MB/s eta 0:00:03
   --------------------- ------------------ 8.3/15.5 MB 3.4 MB/s eta 0:00:03
   --------------------- ------------------ 8.4/15.5 MB 3.3 MB/s eta 0:00:03
   --------------------- ------------------ 8.4/15.5 MB 3.3 MB/s eta 0:00:03
   --------------------- ------------------ 8.5/15.5 MB 3.2 MB/s eta 0:00:03
   --------------------- ------------------ 8.5/15.5 MB 3.2 MB/s eta 0:00:03
   ---------------------- ----------------- 8.7/15.5 MB 3.2 MB/s eta 0:00:03
   ---------------------- ----------------- 8.7/15.5 MB 3.1 MB/s eta 0:00:03
   ---------------------- ----------------- 8.8/15.5 MB 3.1 MB/s eta 0:00:03
   ---------------------- ----------------- 8.8/15.5 MB 3.1 MB/s eta 0:00:03
   ---------------------- ----------------- 8.8/15.5 MB 3.0 MB/s eta 0:00:03
   ----------------------- ---------------- 9.0/15.5 MB 3.0 MB/s eta 0:00:03
   ----------------------- ---------------- 9.0/15.5 MB 3.0 MB/s eta 0:00:03
   ----------------------- ---------------- 9.0/15.5 MB 2.9 MB/s eta 0:00:03
   ----------------------- ---------------- 9.1/15.5 MB 2.9 MB/s eta 0:00:03
   ----------------------- ---------------- 9.2/15.5 MB 2.8 MB/s eta 0:00:03
   ----------------------- ---------------- 9.2/15.5 MB 2.8 MB/s eta 0:00:03
   ----------------------- ---------------- 9.2/15.5 MB 2.8 MB/s eta 0:00:03
   ----------------------- ---------------- 9.2/15.5 MB 2.8 MB/s eta 0:00:03
   ----------------------- ---------------- 9.2/15.5 MB 2.8 MB/s eta 0:00:03
   ----------------------- ---------------- 9.3/15.5 MB 2.7 MB/s eta 0:00:03
   ------------------------ --------------- 9.3/15.5 MB 2.6 MB/s eta 0:00:03
   ------------------------ --------------- 9.3/15.5 MB 2.6 MB/s eta 0:00:03
   ------------------------ --------------- 9.3/15.5 MB 2.6 MB/s eta 0:00:03
   ------------------------ --------------- 9.3/15.5 MB 2.6 MB/s eta 0:00:03
   ------------------------ --------------- 9.3/15.5 MB 2.6 MB/s eta 0:00:03
   ------------------------ --------------- 9.3/15.5 MB 2.6 MB/s eta 0:00:03
   ------------------------ --------------- 9.3/15.5 MB 2.4 MB/s eta 0:00:03
   ------------------------ --------------- 9.4/15.5 MB 2.4 MB/s eta 0:00:03
   ------------------------ --------------- 9.5/15.5 MB 2.4 MB/s eta 0:00:03
   ------------------------ --------------- 9.6/15.5 MB 2.4 MB/s eta 0:00:03
   ------------------------ --------------- 9.6/15.5 MB 2.4 MB/s eta 0:00:03
   ------------------------- -------------- 9.7/15.5 MB 2.3 MB/s eta 0:00:03
   ------------------------- -------------- 9.8/15.5 MB 2.3 MB/s eta 0:00:03
   ------------------------- -------------- 10.0/15.5 MB 2.3 MB/s eta 0:00:03
   ------------------------- -------------- 10.1/15.5 MB 2.3 MB/s eta 0:00:03
   -------------------------- ------------- 10.2/15.5 MB 2.3 MB/s eta 0:00:03
   --------------------------- ------------ 10.5/15.5 MB 2.3 MB/s eta 0:00:03
   --------------------------- ------------ 10.8/15.5 MB 2.3 MB/s eta 0:00:03
   ---------------------------- ----------- 11.1/15.5 MB 2.3 MB/s eta 0:00:02
   ----------------------------- ---------- 11.6/15.5 MB 2.3 MB/s eta 0:00:02
   ------------------------------ --------- 11.9/15.5 MB 2.3 MB/s eta 0:00:02
   ------------------------------- -------- 12.2/15.5 MB 2.3 MB/s eta 0:00:02
   -------------------------------- ------- 12.5/15.5 MB 2.3 MB/s eta 0:00:02
   -------------------------------- ------- 12.7/15.5 MB 2.3 MB/s eta 0:00:02
   --------------------------------- ------ 13.1/15.5 MB 2.3 MB/s eta 0:00:02
   ---------------------------------- ----- 13.4/15.5 MB 2.4 MB/s eta 0:00:01
   ----------------------------------- ---- 13.8/15.5 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 14.4/15.5 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 14.9/15.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  15.5/15.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  15.5/15.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 15.5/15.5 MB 2.4 MB/s eta 0:00:00
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
   ---------------------------------------- 0.0/505.5 kB ? eta -:--:--
   ------------------------- ------------- 327.7/505.5 kB 19.8 MB/s eta 0:00:01
   ---------------------------------------- 505.5/505.5 kB 8.0 MB/s eta 0:00:00
Downloading tzdata-2023.4-py2.py3-none-any.whl (346 kB)
   ---------------------------------------- 0.0/346.6 kB ? eta -:--:--
   --------------------------------------- 346.6/346.6 kB 10.8 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-1.26.4 pandas-2.2.0 pytz-2024.1 tzdata-2023.4
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install pandas

Collecting pandas
  Using cached pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Using cached pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Installing collected packages: pytz, pandas
Successfully installed pandas-2.2.3 pytz-2025.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [5]:
pip install Pyarrow

Collecting PyarrowNote: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  Downloading pyarrow-20.0.0-cp313-cp313-win_amd64.whl.metadata (3.4 kB)
Downloading pyarrow-20.0.0-cp313-cp313-win_amd64.whl (25.7 MB)
   ---------------------------------------- 0.0/25.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/25.7 MB ? eta -:--:--
   -- ------------------------------------- 1.3/25.7 MB 3.9 MB/s eta 0:00:07
   --- ------------------------------------ 2.1/25.7 MB 3.8 MB/s eta 0:00:07
   ---- ----------------------------------- 3.1/25.7 MB 4.1 MB/s eta 0:00:06
   ------ --------------------------------- 3.9/25.7 MB 4.1 MB/s eta 0:00:06
   ------- -------------------------------- 5.0/25.7 MB 4.1 MB/s eta 0:00:05
   --------- ------------------------------ 6.0/25.7 MB 4.4 MB/s eta 0:00:05
   ----------- ---------------------------- 7.3/25.7 MB 4.5 MB/s eta 0:00:05
   ------------- -------------------------- 8.7/25.7 MB 4.6 MB/s eta 0:00:04
   -------------- ------------------------- 9.4/25.7 MB 4.7 MB/s eta 0:00:04
   --------------- ------------------------ 10.2/25.7 MB 4.5 MB/s eta 0:00:04
   ----------------- ---------------------- 11.5/25.7 MB 4.7 MB/s eta 0:00:04
   ------------------- -------------------- 12.3/25.7 MB 4.6 MB/s eta 0:00:03
   --------------------- ------------------ 13.6/25.7 MB 4.7 MB/s eta 0:00:03
   ----------------------- ---------------- 15.2/25.7 MB 4.9 MB/s eta 0:00:03
   -------------------------- ------------- 16.8/25.7 MB 5.1 MB/s eta 0:00:02
   ---------------------------- ----------- 18.1/25.7 MB 5.1 MB/s eta 0:00:02
   ------------------------------ --------- 19.7/25.7 MB 5.3 MB/s eta 0:00:02
   ------------------------------- -------- 20.4/25.7 MB 5.2 MB/s eta 0:00:01
   --------------------------------- ------ 21.2/25.7 MB 5.2 MB/s eta 0:00:01
   ------------------------------------ --- 23.3/25.7 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  25.2/25.7 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------  25.4/25.7 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 25.7/25.7 MB 5.3 MB/s eta 0:00:00
Installing collected packages: Pyarrow
Successfully installed Pyarrow-20.0.0

pandas data table representation
<img src="https://pandas.pydata.org/docs/_images/01_table_dataframe.svg" style="background-color: white;"><br>
To manually store data in a table, create a DataFrame. When using a Python dictionary of lists, the dictionary keys will be used as column headers and the values in each list as columns of the DataFrame.
<br>A DataFrame is a 2-dimensional data structure that can store data of different types (including characters, integers, floating point values, categorical data and more) in columns. It is similar to a spreadsheet, a SQL table or the data.frame in R.

In [16]:
pip install --upgrade pandas

Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (2.2.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy<2,>=1.26.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2023.4)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [6]:
print(pd.Series)
print(pd.DataFrame)

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [ ]:
import pandas as pd

data = {
    "Name": {
        'first_name': ["Braund, Mr. Owen Harris", "Allen, Mr. William Henry", "Bonnell, Miss. Elizabeth"],
        'last_name': ["Braund, Mr. Owen Harris", "Allen, Mr. William Henry", "Bonnell, Miss. Elizabeth"]
    },
    "Python": [22, 35, 58],
    "Machine Learning": [60, 70, 84]
}

# Create a MultiIndex from the 'Name' dictionary
arrays = [data["Name"]['first_name'], data["Name"]['last_name']]
multi_index = pd.MultiIndex.from_arrays( arrays, names = ['first_name', 'last_name'])

# Create the DataFrame with the MultiIndex
df = pd.DataFrame(data={"Python": data["Python"], "Machine Learning": data["Machine Learning"]}, index=multi_index)

print(df)

                                                   Python  Machine Learning
first_name               last_name
Braund, Mr. Owen Harris  Braund, Mr. Owen Harris       22                60
Allen, Mr. William Henry Allen, Mr. William Henry      35                70
Bonnell, Miss. Elizabeth Bonnell, Miss. Elizabeth      58                84

In [5]:
import pandas as pd
df = pd.DataFrame({"Name": {'first_name':["Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",],'last_name':["Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",]    
},"Python" : [22, 35, 58],"Machine Learning" : [60,70,84]
})

ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.

In [4]:
df = {"Name": ["Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",    
        ],"Python" : [22, 35, 58],"Machine Learning" : [60,70,84]
}

In [6]:
print(df)

{'Name': ['Braund, Mr. Owen Harris', 'Allen, Mr. William Henry', 'Bonnell, Miss. Elizabeth'], 'Python': [22, 35, 58], 'Machine Learning': [60, 70, 84]}

In [24]:
data =[
    ["Pratik", 89, 90],
    ["Purvesh", 78, 59],
    ["Jay", 75, 89],
    ["Sandesh", 89, 78],
    ["Raj", 89, 76]
]

colname = ["Name", "Python", "Machine Learning"]

df2 = pd.DataFrame(data, columns=colname)

In [25]:
df

                       Name  Python  Machine Learning
0   Braund, Mr. Owen Harris      22                60
1  Allen, Mr. William Henry      35                70
2  Bonnell, Miss. Elizabeth      58                84

In [26]:
df['Name']

0     Braund, Mr. Owen Harris
1    Allen, Mr. William Henry
2    Bonnell, Miss. Elizabeth
Name: Name, dtype: object

In [28]:
names = ["Jay", "Kumar", "Suraj", "Divya", "Raj"]
s1 = pd.Series(data=names,index=['a','b','c','d','e'])

In [11]:
d = {
    "a":"Jay",
    "b": "Kumar",
    "c": "Suraj",
    "d": "Divya",
    "e": "Raj"
}

s2 = pd.Series(d,name="names")

In [15]:
df3 = pd.DataFrame(s2)
df3

   names
a    Jay
b  Kumar
c  Suraj
d  Divya
e    Raj

In [41]:
df3.names == 'Raj' # Searching Raj inside DataFrame It gives the Bool Series

a    False
b    False
c    False
d    False
e     True
Name: names, dtype: bool

In [16]:
df3[df3.names=="Raj"] # To get the Data

  names
e   Raj

In [17]:
data = {
    "Name":["Pratik", "Purvesh", "Jay", "Sandesh", "Raj"],
    "Python": [89, 78, 75, 89, 89],
    "Machine Learning": [90, 59, 89, 78, 76]
}

df= pd.DataFrame(data, index=["rank1", "rank2", "rank3", "rank4", "rank5"])

In [18]:
df

          Name  Python  Machine Learning
rank1   Pratik      89                90
rank2  Purvesh      78                59
rank3      Jay      75                89
rank4  Sandesh      89                78
rank5      Raj      89                76

In [19]:
import numpy as np # Generating Data with the help of numpy 
data=np.random.randn(10, 4) #random value between 0 and 1 and shape of 10 row and 4 col
data

array([[-0.24727185, -0.38315918,  0.23029262, -1.73836488],
       [ 0.01419774, -0.84823089,  0.86452841, -0.40077789],
       [-0.98308985,  0.35158297,  0.28535121,  0.45561591],
       [ 0.31459918, -1.25011983, -0.73690433,  1.32431929],
       [ 0.00964587,  0.0740468 , -1.58236154,  1.11769718],
       [-0.09464346, -0.73845018, -0.3634173 ,  0.31732341],
       [ 0.12942693,  1.10479104, -0.39186369, -0.52808057],
       [-0.43082486,  1.50791878,  1.27797409, -0.94218773],
       [-0.72728967,  1.15814636, -2.0077282 , -1.83531798],
       [-0.05861493, -0.70186135, -0.37330243,  0.94032665]])

In [20]:
print(df[['Name',"Python"]])# to access multiple series

          Name  Python
rank1   Pratik      89
rank2  Purvesh      78
rank3      Jay      75
rank4  Sandesh      89
rank5      Raj      89

# Load Data From CSV

pandas provides the read_csv() function to read data stored as a csv file into a pandas DataFrame. pandas supports many different file formats or data sources out of the box (csv, excel, sql, json, parquet, …), each of them with the prefix read_*.

In [2]:
pip install pandas

Collecting pandas
  Using cached pandas-2.2.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy<2,>=1.26.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Using cached pandas-2.2.1-cp312-cp312-win_amd64.whl (11.5 MB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.1 pytz-2024.1 tzdata-2024.1
Note: you may need to restart the kernel to use updated packages.

In [24]:
pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-0.3.12-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: packaging in c:\users\admin\appdata\roaming\python\python313\site-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (2.32.3)
Collecting tqdm (from kagglehub)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (2025.1.31)
Requirement already satisfied: colorama in c:\users\admin\appdata\roaming\python\python313\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-0.3.12-py3-none-any.whl (67 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, kagglehub
Successfully installed kagglehub-0.3.12 tqdm-4.67.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("khushikyad001/screen-time-and-app-usage-dataset-iosandroid")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/khushikyad001/screen-time-and-app-usage-dataset-iosandroid?dataset_version_number=1...

100%|██████████| 153k/153k [00:00<00:00, 257kB/s]

Extracting files...
Path to dataset files: C:\Users\admin\.cache\kagglehub\datasets\khushikyad001\screen-time-and-app-usage-dataset-iosandroid\versions\1

In [1]:
import pandas as pd
# df = pd.read_csv("customer and payments.csv")
# df = pd.read_csv(r"C:\Users\admin\Project\Jupyter Projects\customer and payments.csv")
df = pd.read_csv(r"screen_time_app_usage_dataset.csv")

Getting data in to pandas from many different file formats or data sources is supported by read_* functions.

Exporting data out of pandas is provided by different to_*methods.

The head/tail/info methods and the dtypes attribute are convenient for a first check.

### Know your DataFrame

In [2]:
df.dtypes

user_id               int64
date                 object
app_name             object
category             object
screen_time_min     float64
launches              int64
interactions          int64
is_productive          bool
youtube_views       float64
youtube_likes       float64
youtube_comments    float64
extra_col_11        float64
extra_col_12        float64
extra_col_13        float64
extra_col_14        float64
extra_col_15        float64
extra_col_16        float64
extra_col_17        float64
extra_col_18        float64
extra_col_19        float64
extra_col_20        float64
extra_col_21        float64
extra_col_22        float64
extra_col_23        float64
dtype: object

In [193]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     32 non-null     int64
 1   first_name      32 non-null     object
 2   last_name       32 non-null     object
 3   email           32 non-null     object
 4   phone           32 non-null     object
 5   address         32 non-null     object
 6   payment_id      30 non-null     float64
 7   payment_date    30 non-null     object
 8   amount          30 non-null     float64
 9   payment_method  30 non-null     object
dtypes: float64(2), int64(1), object(7)
memory usage: 2.6+ KB

In [3]:
df.columns

Index(['user_id', 'date', 'app_name', 'category', 'screen_time_min',
       'launches', 'interactions', 'is_productive', 'youtube_views',
       'youtube_likes', 'youtube_comments', 'extra_col_11', 'extra_col_12',
       'extra_col_13', 'extra_col_14', 'extra_col_15', 'extra_col_16',
       'extra_col_17', 'extra_col_18', 'extra_col_19', 'extra_col_20',
       'extra_col_21', 'extra_col_22', 'extra_col_23'],
      dtype='object')

In [7]:
df.rename(columns={'date':"date_time"},inplace=True)

In [8]:
df

,user_id,date_time,app_name,category,screen_time_min,launches,interactions,is_productive,youtube_views,youtube_likes,...,extra_col_14,extra_col_15,extra_col_16,extra_col_17,extra_col_18,extra_col_19,extra_col_20,extra_col_21,extra_col_22,extra_col_23
0,1051,2024-01-01 00:00:00.000000000,Camera,Utilities,24.53,2,7,False,NaN,NaN,...,33.43,49.03,64.74,49.49,47.64,38.34,39.56,49.14,62.18,55.91
1,1088,2024-01-01 00:43:41.673891297,Chrome,Utilities,19.78,3,2,False,NaN,NaN,...,44.06,49.40,66.63,62.10,47.64,51.88,42.35,55.86,45.96,46.69
2,1052,2024-01-01 01:27:23.347782594,Spotify,Entertainment,32.03,1,6,False,NaN,NaN,...,55.18,41.87,54.84,65.59,61.28,49.51,41.11,55.53,44.13,71.01
3,1028,2024-01-01 02:11:05.021673891,Google Maps,Utilities,19.10,2,5,False,NaN,NaN,...,59.39,47.87,54.68,56.14,63.98,46.75,46.98,40.15,48.11,50.09
4,1034,2024-01-01 02:54:46.695565188,Instagram,Social,25.19,1,5,False,NaN,NaN,...,51.58,60.38,51.23,44.38,52.71,58.19,37.47,55.64,51.60,37.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,1086,2024-03-31 21:05:13.304434812,Camera,Utilities,9.91,2,3,False,NaN,NaN,...,60.29,63.28,36.44,45.08,39.41,35.40,53.36,50.18,57.08,62.56
2996,1068,2024-03-31 21:48:54.978326109,Netflix,Entertainment,3.40,4,2,False,NaN,NaN,...,47.08,37.49,47.07,47.62,84.89,39.67,49.44,27.34,35.56,64.81
2997,1081,2024-03-31 22:32:36.652217406,Microsoft Teams,Productivity,17.18,2,6,True,NaN,NaN,...,44.27,57.20,52.23,55.06,59.39,56.39,36.01,59.60,56.91,49.69
2998,1038,2024-03-31 23:16:18.326108703,WhatsApp,Social,149.72,3,5,False,NaN,NaN,...,58.51,61.85,50.46,39.00,64.67,55.52,36.53,69.78,37.57,47.29
2999,1089,2024-04-01 00:00:00.000000000,Gmail,Utilities,18.50,1,2,False,NaN,NaN,...,34.99,54.42,43.67,57.42,57.47,29.89,57.10,53.50,44.21,46.26

DataFrame.shape is an attribute ,do not use parentheses for attributes of a pandas Series and DataFrame containing the number of rows and columns: (nrows, ncolumns). A pandas Series is 1-dimensional and only the number of rows is returned.

In [9]:
print("Total Dimention",df.ndim)
print("Shape",df.shape)
print("Total number of element",df.size)

Total Dimention 2
Shape (3000, 24)
Total number of element 72000

In [27]:
df.head() #head() shows the top 5 rows the number of record can be specified 
df.head(3)
# df["youtube_comments"]

,user_id,date_time,app_name,category,screen_time_min,launches,interactions,is_productive,youtube_views,youtube_likes,...,extra_col_14,extra_col_15,extra_col_16,extra_col_17,extra_col_18,extra_col_19,extra_col_20,extra_col_21,extra_col_22,extra_col_23
0,1051,2024-01-01 00:00:00.000000000,Camera,Utilities,24.53,2,7,False,NaN,NaN,...,33.43,49.03,64.74,49.49,47.64,38.34,39.56,49.14,62.18,55.91
1,1088,2024-01-01 00:43:41.673891297,Chrome,Utilities,19.78,3,2,False,NaN,NaN,...,44.06,49.40,66.63,62.10,47.64,51.88,42.35,55.86,45.96,46.69
2,1052,2024-01-01 01:27:23.347782594,Spotify,Entertainment,32.03,1,6,False,NaN,NaN,...,55.18,41.87,54.84,65.59,61.28,49.51,41.11,55.53,44.13,71.01

Indexing and Slicing

In [198]:
df.tail() #tail() same as head difference is that it fetch from last
df.tail(3)

,customer_id,first_name,last_name,email,phone,address,payment_id,payment_date,amount,payment_method
29,20,Ira,Pillai,ira.pillai@email.com,91-09876-54321,"808 Tagore Lane, Ludhiana",40.0,2024-03-10,45.0,Cash
30,21,Ranjan,Tiwari,tiwari@google.com,+91 9359208460,Mumbai Maharastra,NaN,NaN,NaN,NaN
31,22,Rameshwari,Saluke,SalukeRamesh@mail.com,+91 2349282912,Pune Maharastra,NaN,NaN,NaN,NaN

### Access Values

In [13]:
print(df["app_name"][1])
print(df.iloc[2,1]) #accessing row it uses number for idntifying position value

Chrome
2024-01-01 01:27:23.347782594

The inner square brackets define a Python list with column names, whereas the outer brackets are used to select the data from a pandas DataFrame as seen in the previous example.

In [23]:
print(df.loc[:3,["app_name",'category']]) #accesing with slicing and specific columns
print('\n\n\n This is using query() \n')
print((df.query('app_name=="Spotify"')[['date_time','app_name']])) #To select multiple columns, use a list of column names within the selection brackets []

      app_name       category
0       Camera      Utilities
1       Chrome      Utilities
2      Spotify  Entertainment
3  Google Maps      Utilities



 This is using query()

                          date_time app_name
2     2024-01-01 01:27:23.347782594  Spotify
33    2024-01-02 00:01:55.238412804  Spotify
42    2024-01-02 06:35:10.303434478  Spotify
84    2024-01-03 13:10:20.606868956  Spotify
125   2024-01-04 19:01:49.236412137  Spotify
...                             ...      ...
2906  2024-03-29 04:16:24.328109370  Spotify
2927  2024-03-29 19:33:59.479826609  Spotify
2940  2024-03-30 05:02:01.240413471  Spotify
2984  2024-03-31 13:04:34.891630544  Spotify
2992  2024-03-31 18:54:08.282760921  Spotify

[159 rows x 2 columns]

### Apply Condition

In [201]:
name='Rajput'
df.query("last_name == @name ")

,customer_id,first_name,last_name,email,phone,address,payment_id,payment_date,amount,payment_method
14,8,Sanya,Rajput,sanya.rajput@email.com,91-21098-76543,"505 Patel Street, Ahmedabad",28.0,2024-02-15,110.0,Cash
15,8,Sanya,Rajput,sanya.rajput@email.com,91-21098-76543,"505 Patel Street, Ahmedabad",48.0,2024-03-26,120.0,Cash

In [43]:
in_list_of_value = df[df["first_name"].isin(['Shaan','Arjun'])]
in_list_of_value

,customer_id,first_name,last_name,email,phone,address,payment_id,payment_date,amount,payment_method
4,3,Arjun,Sharma,arjun.sharma@email.com,91-76543-21098,"789 Gandhi Avenue, Bangalore",23.0,2024-02-05,120.0,Credit Card
5,3,Arjun,Sharma,arjun.sharma@email.com,91-76543-21098,"789 Gandhi Avenue, Bangalore",43.0,2024-03-16,95.0,Credit Card
26,17,Shaan,Nair,shaan.nair@email.com,91-32109-87654,"505 Patel Street, Surat",37.0,2024-03-04,85.5,Credit Card

In [202]:
df[(df['first_name']=="Aisha") & (df["amount"]>50)] #logical operator and(&) and or(|)

,customer_id,first_name,last_name,email,phone,address,payment_id,payment_date,amount,payment_method
2,2,Aisha,Kumar,aisha.kumar@email.com,91-87654-32109,"456 Nehru Street, Delhi",22.0,2024-02-03,75.5,PayPal

In [203]:
df.query("`first_name`=='Aisha' and `amount`==75.5")#logical operator and , or with query also make use of backtik `` for column name if there is space or other python keyword

,customer_id,first_name,last_name,email,phone,address,payment_id,payment_date,amount,payment_method
2,2,Aisha,Kumar,aisha.kumar@email.com,91-87654-32109,"456 Nehru Street, Delhi",22.0,2024-02-03,75.5,PayPal

#### set inplace = True

In [204]:
df_copy = df.copy()
df_copy.query("amount>100",inplace=True)
df_copy

,customer_id,first_name,last_name,email,phone,address,payment_id,payment_date,amount,payment_method
4,3,Arjun,Sharma,arjun.sharma@email.com,91-76543-21098,"789 Gandhi Avenue, Bangalore",23.0,2024-02-05,120.0,Credit Card
14,8,Sanya,Rajput,sanya.rajput@email.com,91-21098-76543,"505 Patel Street, Ahmedabad",28.0,2024-02-15,110.0,Cash
15,8,Sanya,Rajput,sanya.rajput@email.com,91-21098-76543,"505 Patel Street, Ahmedabad",48.0,2024-03-26,120.0,Cash
24,15,Reyansh,Thakur,reyansh.thakur@email.com,91-54321-09876,"303 Jinnah Road, Nagpur",35.0,2024-02-29,120.0,Credit Card
28,19,Arnav,Menon,arnav.menon@email.com,91-10987-65432,"707 Azad Road, Thiruvananthapuram",39.0,2024-03-08,110.0,Credit Card

In [205]:
df_copy.reset_index(drop=True)  #to reset index

,customer_id,first_name,last_name,email,phone,address,payment_id,payment_date,amount,payment_method
0,3,Arjun,Sharma,arjun.sharma@email.com,91-76543-21098,"789 Gandhi Avenue, Bangalore",23.0,2024-02-05,120.0,Credit Card
1,8,Sanya,Rajput,sanya.rajput@email.com,91-21098-76543,"505 Patel Street, Ahmedabad",28.0,2024-02-15,110.0,Cash
2,8,Sanya,Rajput,sanya.rajput@email.com,91-21098-76543,"505 Patel Street, Ahmedabad",48.0,2024-03-26,120.0,Cash
3,15,Reyansh,Thakur,reyansh.thakur@email.com,91-54321-09876,"303 Jinnah Road, Nagpur",35.0,2024-02-29,120.0,Credit Card
4,19,Arnav,Menon,arnav.menon@email.com,91-10987-65432,"707 Azad Road, Thiruvananthapuram",39.0,2024-03-08,110.0,Credit Card

### drop Column

In [206]:
df_copy.drop("payment_id",axis=1,inplace=True)

In [207]:
df_copy.drop(columns=["customer_id","last_name"],inplace=True)
#changes are never made inside DataFrame unless there is inplace is set to True

In [208]:
df_copy.reset_index(drop=True,inplace=True)

In [209]:
df_copy.drop(labels='address',axis=1,inplace=True)

In [210]:
df_copy

,first_name,email,phone,payment_date,amount,payment_method
0,Arjun,arjun.sharma@email.com,91-76543-21098,2024-02-05,120.0,Credit Card
1,Sanya,sanya.rajput@email.com,91-21098-76543,2024-02-15,110.0,Cash
2,Sanya,sanya.rajput@email.com,91-21098-76543,2024-03-26,120.0,Cash
3,Reyansh,reyansh.thakur@email.com,91-54321-09876,2024-02-29,120.0,Credit Card
4,Arnav,arnav.menon@email.com,91-10987-65432,2024-03-08,110.0,Credit Card

### Add Column

In [211]:
month = ['fab','fab','fab','mar','mar']
df_copy=df_copy.assign(Payment_month=month) #adding column with assign method # multiple columns can be added to the DataFrame by using " , "

In [212]:
df_copy['average_amount']=0  #adding static Value

In [213]:
df_copy

,first_name,email,phone,payment_date,amount,payment_method,Payment_month,average_amount
0,Arjun,arjun.sharma@email.com,91-76543-21098,2024-02-05,120.0,Credit Card,fab,0
1,Sanya,sanya.rajput@email.com,91-21098-76543,2024-02-15,110.0,Cash,fab,0
2,Sanya,sanya.rajput@email.com,91-21098-76543,2024-03-26,120.0,Cash,fab,0
3,Reyansh,reyansh.thakur@email.com,91-54321-09876,2024-02-29,120.0,Credit Card,mar,0
4,Arnav,arnav.menon@email.com,91-10987-65432,2024-03-08,110.0,Credit Card,mar,0

In [214]:
df_copy.insert(1,'last_name',['yadav','khan','choube','thakur','mirza']) #inserting column to specific Index
df_copy

,first_name,last_name,email,phone,payment_date,amount,payment_method,Payment_month,average_amount
0,Arjun,yadav,arjun.sharma@email.com,91-76543-21098,2024-02-05,120.0,Credit Card,fab,0
1,Sanya,khan,sanya.rajput@email.com,91-21098-76543,2024-02-15,110.0,Cash,fab,0
2,Sanya,choube,sanya.rajput@email.com,91-21098-76543,2024-03-26,120.0,Cash,fab,0
3,Reyansh,thakur,reyansh.thakur@email.com,91-54321-09876,2024-02-29,120.0,Credit Card,mar,0
4,Arnav,mirza,arnav.menon@email.com,91-10987-65432,2024-03-08,110.0,Credit Card,mar,0

### Rename Column

In [137]:
df_copy.columns.values[-1]="Days_since_last_visit"

In [138]:
df_copy

,first_name,last_name,email,phone,payment_date,amount,payment_method,Payment_month,Days_since_last_visit
0,Arjun,yadav,arjun.sharma@email.com,91-76543-21098,2024-02-05,120.0,Credit Card,fab,0
1,Sanya,khan,sanya.rajput@email.com,91-21098-76543,2024-02-15,110.0,Cash,fab,0
2,Reyansh,choube,reyansh.thakur@email.com,91-54321-09876,2024-02-29,120.0,Credit Card,fab,0
3,Arnav,thakur,arnav.menon@email.com,91-10987-65432,2024-03-08,110.0,Credit Card,mar,0
4,Sanya,mirza,sanya.rajput@email.com,91-21098-76543,2024-03-26,120.0,Cash,mar,0

### Data Type Conversion

In [150]:
df_copy.payment_date=pd.to_datetime(df_copy.payment_date).dt # df['payment_date'] = df['payment_date'].apply(pd.to_datetime)
df_copy.amount = df_copy.amount.astype('int')

In [165]:
df_copy.dtypes

first_name                       object
last_name                        object
email                            object
phone                            object
payment_date             datetime64[ns]
amount                            int32
payment_method                   object
Payment_month                    object
Days_since_last_visit           float64
Days_since_last_visit           float64
dtype: object

In [153]:
df_copy

,first_name,last_name,email,phone,payment_date,amount,payment_method,Payment_month,Days_since_last_visit
0,Arjun,yadav,arjun.sharma@email.com,91-76543-21098,2024-02-05,120,Credit Card,fab,0
1,Sanya,khan,sanya.rajput@email.com,91-21098-76543,2024-02-15,110,Cash,fab,0
2,Reyansh,choube,reyansh.thakur@email.com,91-54321-09876,2024-02-29,120,Credit Card,fab,0
3,Arnav,thakur,arnav.menon@email.com,91-10987-65432,2024-03-08,110,Credit Card,mar,0
4,Sanya,mirza,sanya.rajput@email.com,91-21098-76543,2024-03-26,120,Cash,mar,0

### Assign value to series

In [169]:
import numpy as np
df_copy = df_copy.assign(Days_since_last_visit=lambda df:(pd.to_datetime('2024-04-01') - df['payment_date'])/np.timedelta64(1,'D'))
df_copy

,first_name,last_name,email,phone,payment_date,amount,payment_method,Payment_month,Days_since_last_visit
0,Arjun,yadav,arjun.sharma@email.com,91-76543-21098,2024-02-05,120,Credit Card,fab,56.0
1,Sanya,khan,sanya.rajput@email.com,91-21098-76543,2024-02-15,110,Cash,fab,46.0
2,Reyansh,choube,reyansh.thakur@email.com,91-54321-09876,2024-02-29,120,Credit Card,fab,32.0
3,Arnav,thakur,arnav.menon@email.com,91-10987-65432,2024-03-08,110,Credit Card,mar,24.0
4,Sanya,mirza,sanya.rajput@email.com,91-21098-76543,2024-03-26,120,Cash,mar,6.0

In [171]:
df_copy['Months_since_last_visit']=(np.round(df_copy.Days_since_last_visit /31))
df_copy

,first_name,last_name,email,phone,payment_date,amount,payment_method,Payment_month,Days_since_last_visit,Months_since_last_visit
0,Arjun,yadav,arjun.sharma@email.com,91-76543-21098,2024-02-05,120,Credit Card,fab,56.0,2.0
1,Sanya,khan,sanya.rajput@email.com,91-21098-76543,2024-02-15,110,Cash,fab,46.0,1.0
2,Reyansh,choube,reyansh.thakur@email.com,91-54321-09876,2024-02-29,120,Credit Card,fab,32.0,1.0
3,Arnav,thakur,arnav.menon@email.com,91-10987-65432,2024-03-08,110,Credit Card,mar,24.0,1.0
4,Sanya,mirza,sanya.rajput@email.com,91-21098-76543,2024-03-26,120,Cash,mar,6.0,0.0

In [172]:
df_copy.describe()#The describe() method provides a quick overview of the numerical data in a DataFrame. As the Name and Sex columns are textual data, these are by default not taken into account by the describe() method.

,payment_date,amount,Days_since_last_visit,Months_since_last_visit
count,5,5.000000,5.000000,5.000000
mean,2024-02-28 04:48:00,116.000000,32.800000,1.000000
min,2024-02-05 00:00:00,110.000000,6.000000,0.000000
25%,2024-02-15 00:00:00,110.000000,24.000000,1.000000
50%,2024-02-29 00:00:00,120.000000,32.000000,1.000000
75%,2024-03-08 00:00:00,120.000000,46.000000,1.000000
max,2024-03-26 00:00:00,120.000000,56.000000,2.000000
std,NaN,5.477226,19.421637,0.707107

## Drop Rows From DataFrame

By using pandas.DataFrame.drop() method you can drop/remove/delete rows from DataFrame. axis param is used to specify what axis you would like to remove. By default axis = 0 meaning to remove rows. Use axis=1 or columns param to remove columns. By default, Pandas return a copy DataFrame after deleting rows, used inpalce=True to remove from existing referring DataFrame.
DataFrame.drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')

In [174]:
df_copy.drop(index=[1,2]) #inplace is False so this command won't afffect the actual DataFrame instead it returns the filtered output

,first_name,last_name,email,phone,payment_date,amount,payment_method,Payment_month,Days_since_last_visit,Months_since_last_visit
0,Arjun,yadav,arjun.sharma@email.com,91-76543-21098,2024-02-05,120,Credit Card,fab,56.0,2.0
3,Arnav,thakur,arnav.menon@email.com,91-10987-65432,2024-03-08,110,Credit Card,mar,24.0,1.0
4,Sanya,mirza,sanya.rajput@email.com,91-21098-76543,2024-03-26,120,Cash,mar,6.0,0.0

In [180]:
df_copy.drop(index=[0,1],axis=0)   #Delete row by index

,first_name,last_name,email,phone,payment_date,amount,payment_method,Payment_month,Days_since_last_visit,Months_since_last_visit
2,Reyansh,choube,reyansh.thakur@email.com,91-54321-09876,2024-02-29,120,Credit Card,fab,32.0,1.0
3,Arnav,thakur,arnav.menon@email.com,91-10987-65432,2024-03-08,110,Credit Card,mar,24.0,1.0
4,Sanya,mirza,sanya.rajput@email.com,91-21098-76543,2024-03-26,120,Cash,mar,6.0,0.0

In [183]:
df_copy.drop(df_copy.index[0:3])   ## Delete Rows by Index Range
df_copy.drop(range(0,3))            # Delete row using range function

,first_name,last_name,email,phone,payment_date,amount,payment_method,Payment_month,Days_since_last_visit,Months_since_last_visit
3,Arnav,thakur,arnav.menon@email.com,91-10987-65432,2024-03-08,110,Credit Card,mar,24.0,1.0
4,Sanya,mirza,sanya.rajput@email.com,91-21098-76543,2024-03-26,120,Cash,mar,6.0,0.0

In [224]:

# Iterate all rows using DataFrame.iterrows()
print("After iterating all rows:\n")

for index, row in df_copy.iterrows():
    print (f"{index} {(row["first_name"]).ljust(15," ")} paid {row["amount"]} on {row["payment_date"]}") #The ljust method means "left-justify"; this makes sense because your string will be to the left after adjustment up to the specified length.

After iterating all rows:

0 Arjun           paid 120.0 on 2024-02-05
1 Sanya           paid 110.0 on 2024-02-15
2 Sanya           paid 120.0 on 2024-03-26
3 Reyansh         paid 120.0 on 2024-02-29
4 Arnav           paid 110.0 on 2024-03-08

### Append DataFrame

In [2]:
df1 = pd.read_csv(r"C:\Users\admin\Project\Jupyter Projects\customer and payments.csv")
df2 = pd.read_csv(r"C:\Users\admin\Project\Jupyter Projects\customer and payments.csv")
df3 = pd.concat([df1,df2])

In [3]:
df3.shape

(64, 10)

## Drop Duplicates
Pandas DataFrame.drop_duplicates() function is used to remove duplicates from the DataFrame rows and columns. When data preprocessing and analysis step, data scientists need to check for any duplicate data is present, if so need to figure out a way to remove the duplicates.

In [5]:
df3.drop_duplicates().shape

(32, 10)

### Groupby

In [15]:
result = df.groupby(by="first_name",sort=False).count()
result.customer_id

first_name
Aarav         2
Aisha         2
Arjun         2
Ishika        2
Rohan         2
Ananya        2
Aryan         2
Sanya         2
Vivaan        2
Zara          2
Aaradhya      1
Vihaan        1
Advait        1
Myra          1
Reyansh       1
Ishani        1
Shaan         1
Zoya          1
Arnav         1
Ira           1
Ranjan        1
Rameshwari    1
Name: customer_id, dtype: int64

In [30]:
print(df.groupby(by=["payment_method",'first_name'])['amount'].aggregate(['min','max','sum','count']))
print(result.dtypes)
print(df.groupby('payment_method')['amount'].mean())

                              min     max     sum  count
payment_method first_name
Cash           Ira          45.00   45.00   45.00      1
               Ishani       50.00   50.00   50.00      1
               Ishika       32.50   45.00   77.50      2
               Sanya       110.00  120.00  230.00      2
               Vihaan       40.50   40.50   40.50      1
Credit Card    Aaradhya     80.00   80.00   80.00      1
               Aarav        60.00  100.00  160.00      2
               Advait       65.00   65.00   65.00      1
               Arjun        95.00  120.00  215.00      2
               Arnav       110.00  110.00  110.00      1
               Aryan        28.00   30.50   58.50      2
               Reyansh     120.00  120.00  120.00      1
               Rohan        78.25   90.25  168.50      2
               Shaan        85.50   85.50   85.50      1
               Vivaan       75.75   90.75  166.50      2
PayPal         Aisha        42.75   75.50  118.25      2
               Ananya       55.50   60.00  115.50      2
               Myra         95.25   95.25   95.25      1
               Zara         55.00   62.00  117.00      2
               Zoya         70.25   70.25   70.25      1
customer_id       int64
last_name         int64
email             int64
phone             int64
address           int64
payment_id        int64
payment_date      int64
amount            int64
payment_method    int64
dtype: object
payment_method
Cash           63.285714
Credit Card    81.933333
PayPal         64.531250
Name: amount, dtype: float64

<img src="https://pandas.pydata.org/docs/_images/02_io_readwrite.svg" style="background-color : white">

In [39]:
df.to_csv("result.csv", index=False)

In [8]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)
df4 = pd.DataFrame(
    {
        "B": ["B2", "B3", "B6", "B7"],
        "D": ["D2", "D3", "D6", "D7"],
        "F": ["F2", "F3", "F6", "F7"],
    },
    index=[2, 3, 6, 7],
)
pd.concat([df1,df4],axis=1,join="outer")

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7